project_b_06/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('team_b_06.urls')),
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('team_b_06.urls')),
]

team_b_06/urls.py
from django.urls import path
from . import views
from django.urls import path
from .views import profile, SignUpView, add_details, profile_view
from django.contrib import admin


urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/profile/', profile_view, name='profile'),
    path('accounts/login/', views.signin, name='login'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('report/', views.report, name='report'),
    path('report/confirmation/', views.confirmation, name='confirmation'),
    path('reports/', views.view_reports, name='view_reports'),
    path('report/<int:report_id>/', views.report_detail, name='report_detail'),
    path('report/delete/<int:report_id>/', views.delete_report, name='delete_report'),
    path('report/<int:report_id>/approve/', views.report_approve, name='report_approve'),
    path('report/<int:report_id>/instructor', views.instructor_approve, name='instructor_approve'),
    path('report/<int:report_id>/send', views.send_instructor, name='send_instructor'),
    path('submission_history/', views.submission_history, name='submission_history'),
    path('resolve/<int:report_id>/', views.resolve_report, name = "resolve_report"), 
    path('public_reports/', views.public_reports, name='public_reports'),
    path('instructor_reports/', views.instructor_reports, name='instructor_reports'),
    path('account/add_details/', add_details, name='add_details'),
]

team_b_06/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MaxValueValidator
import datetime
from django.core.validators import RegexValidator

alpha = RegexValidator(r'^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')
alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    role = models.CharField(max_length=30, default='Student')
    site_admin = models.BooleanField(default=False)
    comp_id = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Report(models.Model):
    TAG_CHOICES = (
        ("N", "None"),
        ("CC", "Classroom Conduct/Behavior"),
        ("GR", "Grading"),
        ("SM", "Subject Material"),
        ("AI", "Accessibility and Inclusivity"),
        ("GF", "General Feedback"),
        ("O", "Other")
    )

    mnemonic = models.CharField(max_length=4, validators=[alpha])
    number = models.IntegerField(default=0, validators=[MaxValueValidator(9999)])
    reported_fname = models.CharField(max_length=20)
    reported_lname = models.CharField(max_length=20)
    reported_comp_id = models.CharField(max_length=7, validators=[alphanumeric])
    reporter_comp_id = models.CharField(max_length=30, default='')
    #True is public, False is private
    whisteblower_approved = models.BooleanField(default=False)
    admin_approved = models.BooleanField(default=False)
    instructor_approved = models.BooleanField(default=False)
    awaiting_instructor_approval = models.BooleanField(default=False)
    text = models.CharField(max_length=5000)
    title = models.CharField(max_length=100, default = 'No Title (Default)')
    pub_date = models.DateTimeField("date published", default=timezone.now)
    file = models.FileField(upload_to='reports/', blank=True, null=True)
    user = models.ForeignKey(UserProfile, blank=True, null=True, on_delete=models.CASCADE) # user linked to report
    status = models.CharField(max_length=100, default="New")  # new, in progress, or resolved
    note = models.TextField(default="")
    submit_date = models.DateField(default=datetime.date.today)
    tag = models.CharField(max_length=5000, choices=TAG_CHOICES, default="N")
    def __str__(self):
        return   self.reported_comp_id

team_b_06/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserCreationForm, LoginForm, SignupForm, ReportForm, ResolveReportForm, ProfileForm
from django.urls import reverse_lazy
from django.views import generic
from django.template import loader
from django.utils import timezone
from .models import *
from django.core.exceptions import PermissionDenied
from .models import Report
from django.shortcuts import get_object_or_404
from django.conf import settings
import boto3

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

def home(request):
    return render(request, 'project_b_06/home.html')

@login_required
def profile(request):
    if request.user.is_authenticated:
        if request.user.profile.site_admin == False:
            reports = Report.objects.filter(user=request.user.profile)
        else:
            reports = Report.objects.none()
    else:
        reports = Report.objects.none()
    return render(request, 'project_b_06/profile.html', {'user_profile': request.user.profile, 'user':request.user, 'reports':reports})


def signin(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('add_details')
            else:
                # Add an explicit error message if authentication fails
                form.add_error(None, "Invalid username or password")
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            request.user.role = form.cleaned_data.get('role')
            user = form.save()
            profile = user.profile
            profile.role = form.cleaned_data['role']
            profile.comp_id = form.cleaned_data['password']
            profile.save()
            return redirect('login')
        else:
            return render(request, 'account/signup.html', {'form': form})
    else:
        form = SignupForm()
    return render(request, 'account/signup.html',{'form': form})

def add_details(request):
    user_id = request.user.id
    user = User.objects.get(id=user_id)

    # if user already has set their computing id, redirect to profile page
    if user.profile.comp_id:
        return redirect('profile')

    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=user.profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ProfileForm(instance=user.profile)
    return render(request, 'account/add_details.html', {'form': form})

@login_required
def profile_view(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        form.fields.pop('comp_id', None)
        if form.is_valid():
            form.save()
    else:
        form = ProfileForm(instance=request.user.profile)
        form.fields.pop('comp_id', None)
    
    if request.user.is_authenticated:
        if request.user.profile.site_admin == False:
            reports = Report.objects.filter(user=request.user.profile)
        else:
            reports = Report.objects.none()
    else:
        reports = Report.objects.none()

    user_profile = request.user.profile
    context = {
        'form': form,
        'user_profile': user_profile,
        'reports': reports,
    }
    return render(request, 'project_b_06/profile.html', context)


def admin_login(request):
    return render(request, 'admin:index')
def logout_view(request):
    logout(request)
    return redirect('home')

def report(request):
    if request.method == 'POST':
        form = ReportForm(request.POST, request.FILES)
        if form.is_valid():
            mnemonic = form.cleaned_data['mnemonic']
            number = form.cleaned_data['number']
            reported_fname = form.cleaned_data['reported_fname']
            reported_lname = form.cleaned_data['reported_lname']
            reported_comp_id = form.cleaned_data['reported_comp_id']
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            whisteblower_approved = form.cleaned_data['whisteblower_approved']
            admin_approved = False
            staff_approved = False
            pub_date = timezone.now()
            file = form.cleaned_data['file']
            tag = form.cleaned_data['tag']

            if request.user.is_authenticated:
                user = request.user.profile
                reporter_comp_id = user.comp_id
            else:
                user = None
                reporter_comp_id = 'Anonymous'
                
            report = Report(
                mnemonic=mnemonic,
                number=number,
                reported_fname=reported_fname,
                reported_lname=reported_lname,
                reported_comp_id=reported_comp_id,
                reporter_comp_id = reporter_comp_id,
                whisteblower_approved=whisteblower_approved,
                title=title,
                text=text,
                pub_date=pub_date,
                file=file,
                user=user,
                tag=tag
            )
            report.save()
            return redirect('confirmation')  
        else:
            return render(request, 'project_b_06/report.html', {'form': form})
    else:
        form = ReportForm()
    return render(request, 'project_b_06/report.html',  {'form': form})

def confirmation(request):
    latest_report = Report.objects.order_by("-pub_date").first()
    context = { "latest_report": latest_report }
    return render(request, 'project_b_06/confirmation.html', context)

def view_reports(request):
    if request.user.is_authenticated:
        if request.user.profile.site_admin:
            reports = Report.objects.all()
        else:
            reports = Report.objects.filter(whisteblower_approved=True)
    else:
        reports = Report.objects.filter(whisteblower_approved=True)

    return render(request, 'project_b_06/view_reports.html', {'reports': reports})

def report_detail(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    if (request.user.is_authenticated):
        if (request.user.profile.site_admin):
            if report.status == ("New"):
                report.status = "In Progress"
                report.save(update_fields=['status'])

    if report.file:  # Check if a file is associated with the report
        url = f"https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/reports/{report.file.name}"
    else:
        url = None  # No file is associated with the report
    is_admin = False
    if request.user.is_authenticated:
        is_admin = request.user.profile.site_admin
    public = report.whisteblower_approved

    return render(request, 'project_b_06/report_detail.html', {'report': report, 'url': url, 'is_admin': is_admin, 'public': public, 'is_authenticated': request.user.is_authenticated})

def report_approve(request, report_id):
    report = get_object_or_404(Report, id=report_id)

    report.admin_approved = True
    report.save()

    return redirect('view_reports')

def send_instructor(request, report_id):
    report = get_object_or_404(Report, id=report_id)

    report.awaiting_instructor_approval = True
    report.save()

    return redirect('view_reports')

def instructor_approve(request, report_id):
    report = get_object_or_404(Report, id=report_id)

    if request.user.is_authenticated and report.reported_comp_id == request.user.profile.comp_id:
        report.instructor_approved = True
        report.save()

    return redirect('instructor_reports')

def submission_history(request):
    if request.user.is_authenticated:
        if request.user.profile.site_admin == False:
            reports = Report.objects.filter(user=request.user.profile)
        else:
            reports = Report.objects.none()
    else:
        reports = Report.objects.none()
    return render(request, 'project_b_06/submission_history.html', {'reports': reports})

def delete_report(request, report_id):
    report = Report.objects.get(pk=report_id)
    if request.method == 'POST':
        report = get_object_or_404(Report, id=report_id)
        if request.user.is_authenticated and report.user == request.user.profile:
            report.delete()
            return redirect('profile')
        else:
            raise PermissionDenied("You are not authorized to delete this submission.")
    else:
        pass

def resolve_report(request, report_id):
    report = Report.objects.get(pk=report_id)
    if request.method == 'POST':
        form = ResolveReportForm(request.POST)
        if form.is_valid():
            report.status = "Resolved"
            report.note = form.cleaned_data['note']
            report.save(update_fields = ['status', 'note'])
            return redirect('view_reports')
    else:
        form = ResolveReportForm()
    return render(request, "project_b_06/resolve_report.html", {'report': report, 'form': form})

def public_reports(request):
    reports = Report.objects.filter(whisteblower_approved=True, admin_approved=True, instructor_approved=True)
    return render(request, 'project_b_06/public_reports.html', {'reports': reports})

def instructor_reports(request):

team_b_06/templates/project_b_06/confirmation.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'project_b_06/confirmation.css' %}">
{% endblock %}

{% block content %}
<div class="body-content">
    <div class="col">
        <div class="row">
            <div class="thanks">Thank you for reporting!</div>

            <h4>Your report has been submitted</h4>
        </div>
        <div class="main_content">
            <div class="col">
                <br>
                <div class="rounded_box">
                    {% if latest_report %}
                    <div>
                        <p>Course Mnemonic: {{ latest_report.mnemonic }}</p>
                        <p>Course Number: {{ latest_report.number }}</p>
                        <p>Reported TA/Prof's Computing ID: {{ latest_report.reported_comp_id }}</p>
                        <p>Visibility:
                            {% if latest_report.whisteblower_approved %}
                            Public
                            {% else %}
                            Private
                            {% endif %}
                        </p>
                        <p>Report: {{ latest_report.text }}</p>
                        <p>Submission Date/Time: {{ latest_report.pub_date }}</p>
                        {% if latest_report.whisteblower_approved %}
                            <p style="font-weight: bold;">NOTE: Public reports require approval from the reported instructor and an internal auditor, <br> thus it may take extra time to process the report before being posted in the "Public Reports" tab.</p>
                        {% endif %}
                    </div>
                    {% else %}
                    <p>No reports are available.</p>
                    {% endif %}
                </div>

                <a href="/report" class="button">Submit Another Report</a>
            </div>
        </div>
    </div>

</div>

{% endblock %}

team_b_06/templates/project_b_06/home.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'project_b_06/home.css' %}">
{% endblock %}

{% block content %}
<div class="col">
    <div class="block">

        <div class="main_content">
            <h1>Report-A-Hoo</h1>
            <h3>Have a problem with your instructors? You've come to the right place...</h3>
            <br>

            {% if request.user.profile.role != 'Instructor' and not request.user.profile.site_admin %}
            <a href="{% url 'report' %}" class="btn btn-outline-secondary me-2">Report Now</a>
            {% endif %}
        </div>


        <div class="disclaimer">
            <p>
                Disclaimer: This application is solely intended for educational purposes only.
                It is not to be used for actual whistleblowing or reporting of sensitive or private information.
                The features provided within this app are simulated and do not constitute a secure or confidential
                channel
                for
                reporting misconduct.
                Users are reminded that actual whistleblowing should be carried out through appropriate channels and
                in
                accordance with legal and organizational policies.
                This application does not guarantee anonymity or protection for individuals wishing to disclose
                sensitive
                information.
                The creators and developers of this app do not assume any responsibility for the misuse of the
                application
                or
                any consequences resulting from its use for purposes other than intended.
            </p>
        </div>
    </div>
</div>

{% endblock %}

team_b_06/templates/project_b_06/instructor_reports.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'project_b_06/submission_history.css' %}">
{% endblock %}

{% block content %}

<div class="below">
    <div class="body-content">

        <div class="instruct">
            <h3>
                Reports About You
            </h3>
        </div>


        <div class="disclaimer">
            <p>
                This page is a list of all complaints students have made against you, the instructor.
                For each report, you can view a summary of the report and decide whether you want to
                approve the report or not. Approving the report will allow the report to show up in the 
                public reports tab for everyone to see.
            </p>
        </div>
        
        <div class="shadow-round">
            <div class="pad">
                <table>
                    <thead>
                        <tr>
                            <th style="text-align: center">Title</th>
                            <th style="text-align: center">Date</th>
                            <th style="text-align: center">Instructor Approval</th>
                            <th style="text-align: center">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for report in reports %}
                        <tr>
                            <td style="text-align: center">{{ report.title }}</td>
                            <td>{{ report.pub_date }}</td>
                            {% if report.awaiting_instructor_approval and not report.instructor_approved %}
                            <td>Waiting for Your Approval</td>
                            {% elif report.instructor_approved %}
                            <td>Approved by You</td>
                            {% else %}
                            <td>No status available</td>
                            {% endif %}
                            <td class="centered-column">
                                <span
                                    class="status {% if report.status == 'New' %}new{% elif report.status == 'In Progress' %}in-progress{% elif report.status == 'Resolved' %}resolved{% endif %}">
                                    {{ report.status }}
                                </span>
                            </td>
                            <td><a href="{% url 'report_detail' report.id %}"
                                    class="btn btn-outline-secondary me-2">View</a></td>

                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">No reports found</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        
    </div>

</div>



{% endblock %}

team_b_06/templates/project_b_06/public_reports.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'project_b_06/public.css' %}">
{% endblock %}

{% block content %}
<div class="body-content">

    <h2>Public Reports</h2>
    {% for report in reports %}
    <div class="shadow-round">
        <div class="col">
            <div class="report-row">
                <div class="report-item">
                    <div class="label">Title:</div>
                    <div class="detail">{{ report.title }}</div>
                </div>
                <div class="report-item">
                    <div class="label">Date:</div>
                    <div class="detail">{{ report.pub_date }}</div>
                </div>
                <div class="report-item">
                    <div class="label">Tag:</div>
                    <div class="detail">{{ report.get_tag_display }}</div>
                </div>
            </div>
            <div class="report-row">
                <div class="report-item">
                    <div class="label">Reported About:</div>
                    <div class="detail">{{ report.reported_fname }} {{ report.reported_lname }}</div>
                </div>
                <div class="report-item">
                    <div class="label">Course:</div>
                    <div class="detail">{{ report.mnemonic }} {{ report.number }}</div>
                </div>
                <div class="report-item">
                    <div class="label">Status:</div>
                    <div class="detail">{{ report.status }}</div>
                </div>
            </div>
            <hr>
            <div class="report-item">
                <div class="label">Report Text:</div>
                <div class="detail">{{ report.text }}</div>
            </div>
        </div>
    </div>

    {% empty %}
    <p>No public reports available.</p>
    {% endfor %}
</div>
{% endblock %}

team_b_06/templates/project_b_06/report_detail.html
{% extends 'base.html' %}

{% load static %}
{% load basename %}

{% block head %}
<link rel="stylesheet" href="{% static 'project_b_06/report_detail.css' %}">
{% endblock %}

{% block content %}
<div class="below">
    <div class="body-content">

        <div class="row">
            <div class="col-6">
                <div class="left">
                    <div class="instruct">
                        <h2>
                            {{ report.title }}
                        </h2>
                    </div>
                    <br>

                    <h4>Class:</h4>
                    <p>{{ report.mnemonic }} {{ report.number }}</p>

                    <h4>Report Text:</h4>
                    <p>{{ report.text }}</p>

                    <h4>Tag:</h4>
                    <p>{{report.get_tag_display}}</p>

                    <h4>Auditor's Resolved Note</h4>
                    {% if report.note %}
                    <p>{{ report.note }}</p>
                    {% else %}
                    <p>No resolved note</p>
                    {% endif %}

                    <h4>Attached Files:</h4>
                    {% if url %}
                    <a href="{{ report.file.url }}">{{ report.file.name|basename }}</a>
                    {% else %}
                    <p>No file associated with this report.</p>
                    {% endif %}


                    {% if is_authenticated and not is_admin and request.user.profile.role != 'Instructor' %}
                    <div class="container">
                        <div class="row justify-content-start">
                            <div class="col-auto">
                                <form action="{% url 'delete_report' report.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn">Delete Report</button>
                                </form>
                            </div>
                            <div class="col-auto">
                                <a href="{% url 'profile' %}" class="btn btn-outline-secondary me-2">View
                                    Your
                                    Reports</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    {% if is_authenticated and request.user.profile.role == 'Instructor' %}
                    <div class="container">
                        <div class="row justify-content-start">
                            {% if not report.instructor_approved %}
                            <div class="col-auto">
                                <form action="{% url 'instructor_approve' report.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn">Approve Report</button>
                                </form>
                            </div>
                            {% endif %}
                            <div class="col-auto">
                                <a href="{% url 'instructor_reports' %}" class="btn btn-outline-secondary me-2">View Reports About You</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    {% if is_admin %}
                    <div class="container">
                        <div class="row justify-content-start">
                            <div class="col-auto">
                                {% if report.whisteblower_approved and report.instructor_approved %}
                                <a href="{% url 'report_approve' report_id=report.id %}"
                                    class="btn btn-outline-secondary me-2">Approve</a>
                                {% elif report.whisteblower_approved and not report.instructor_approved and not report.awaiting_instructor_approval  %}
                                <a href="{% url 'send_instructor' report.id %}"
                                    class="btn btn-outline-secondary me-2">Send to Staff for Approval</a>
                                {% endif %}
                            </div>
                            <div class="col-auto">
                                <a href="{%url 'view_reports' %}" class="btn btn-outline-secondary me-2">View All
                                    Reports</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-6">
                <div class="right">
                    <img src="{% static 'project_b_06/images/cartoon_prof.png' %}">
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

team_b_06/templates/project_b_06/resolve_report.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'project_b_06/resolve.css' %}">
{% endblock %}

{% block content %}
<div class="body-content">
    <div class="center-content">
        <div class="shadow-round">
            <div class="title">
                <h2>Resolve Report</h2>
            </div>
            <form class="center-content" action="{% url 'resolve_report' report_id=report.id %}" method="POST">
                <div class="col">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label><br>
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button type="submit">Resolve</button>

                </div>
            </form>

        </div>

    </div>

</div>
{% endblock %}

team_b_06/templates/project_b_06/submission_history.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'project_b_06/submission_history.css' %}">
{% endblock %}

{% block content %}
<div class="below">
    <div class="body-content">

        <div class="instruct">
            <h3>
                Your Reports
            </h3>
        </div>

        <div class="shadow-round">
            <div class="pad">
                <table>
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Reported Person</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Auditor's Resolved Note</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for report in reports %}
                        <tr>
                            <td>{{ report.title }}</td>
                            <td>{{ report.reported_fname }} {{ report.reported_lname }}</td>
                            <td>{{ report.pub_date }}</td>
                            <td class="centered-column">
                                <span
                                    class="status {% if report.status == 'New' %}new{% elif report.status == 'In Progress' %}in-progress{% elif report.status == 'Resolved' %}resolved{% endif %}">
                                    {{ report.status }}
                                </span>
                            </td>
                            <td>{{ report.note }}</td>
                            <td class="centered-column"><a href="{% url 'report_detail' report.id %}"
                                    class="btn btn-outline-secondary me-2">View</a></td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">No reports found</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>



{% endblock %}